version: '3.9'

services:
  mailcamp-db:
    image: postgres:15         # PostgreSQL version
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mailcamp-db      # database name
    ports:
      - "5460:5432"           # map port host:container
    volumes:
      - mailcamp-db:/var/lib/postgresql/data

volumes:
  mailcamp-db:
